name: Run CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, darwin]
        arch: [amd64, arm64]
        compiler: [gcc, clang]
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      - name: Run functional tests
        run:  echo "hello world ${{ matrix.platform }} ${{ matrix.arch}} ${{ matrix.compiler}}"
