name: Run CI

on: [push, pull_request]

jobs:
  linux-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_18_04, ubuntu_20_04]
        arch: [amd64, arm64]
        compiler: [gcc, clang]
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: docker/linux/${{ matrix.os }}
          platforms: linux/${{ matrix.arch }}
          push: false
          load: true
          tags: workflow_test_${{ matrix.os}}_${{ matrix.arch }}:test

      - name: Create script
        uses: ./.github/actions/create-script
        with:
          compiler: ${{ matrix.compiler }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch}}
          filename: sample_script.sh

      - name: Run test inside docker
        run: cat sample_script.sh && cat sample_script.sh | docker run -i --rm -v $PWD:/project workflow_test_${{ matrix.os}}_${{ matrix.arch}}:test bash -c 'source /dev/stdin'

  macos-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:

      - name: Install dependencies
        run: |-
            brew install gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create script
        uses: ./.github/actions/create-script
        with:
          compiler: ${{ matrix.compiler }}
          os: macos
          arch: amd64
          filename: sample_script.sh

      - name: Run test
        run: ./sample_script.sh
